GH Actions, continue on failure (#71)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -54,59 +54,81 @@ jobs:
       - name: "Byte-compile repo"
         run: make setup testsetup
 
+      # If any of the previous steps fail, don't continue
+      # Past this point, allow steps to execute even if previous ones fail
+
       - name: "C sanity"
+      # if: ${{ success() }} 
         run: make c-sanity
 
       - name: "JS sanity"
+        if: ${{ success() || failure() }}
         run: make js-sanity  
       
       - name: "Go sanity"
+        if: ${{ success() || failure() }}
         run: make go-sanity  
       
       - name: "Sollya sanity"
+        if: ${{ success() || failure() }}
         run: make sollya-sanity  
       
       - name: "Z3 sanity"
+        if: ${{ success() || failure() }}
         run: make smtlib2-sanity 
 
       - name: "CakeML sanity"
+        if: ${{ success() || failure() }}
         run: make cml-sanity 
 
       - name: "Wolfram/Mathematica sanity"
+        if: ${{ success() || failure() }}
         run: make wls-sanity
 
       - name: "C test"
+        if: ${{ success() || failure() }}
         run: make c-test
 
       - name: "JS test"
+        if: ${{ success() || failure() }}
         run: make js-test  
       
       - name: "Go test"
+        if: ${{ success() || failure() }}
         run: make go-test  
       
       - name: "Sollya test"
+        if: ${{ success() || failure() }}
         run: make sollya-test  
       
       - name: "Z3 test"
+        if: ${{ success() || failure() }}
         run: make smtlib2-test 
 
       - name: "CakeML test"
+        if: ${{ success() || failure() }}
         run: make cml-test 
 
       - name: "Wolfram/Mathematica test"
+        if: ${{ success() || failure() }}
         run: make wls-test 
 
       - name: "Export tool"
+        if: ${{ success() || failure() }}
         run: make export-test
 
       - name: "Transform tool"
+        if: ${{ success() || failure() }}
         run: make transform-test
 
       - name: "Toolserver tool"
+        if: ${{ success() || failure() }}
         run: make toolserver-test
 
       - name: "Evaluate tool"
+        if: ${{ success() || failure() }}
         run: make evaluate-test
 
       - name: "Raco tests"
+        if: ${{ success() || failure() }}
         run: make raco-test
